name: Deploy Demo

on:
  push:
    branches: [develop, ci-*]
    paths:
      - search_interface/**
      - .github/workflows/deploy_demo.yml

defaults:
  run:
    working-directory: search_interface/

jobs:
  deploy-demo:
    name: Deploy Demo
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Build react app
        run: npm run build
        env:
          PUBLIC_URL: http://cppalliance.org/boost-gecko/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./search_interface/build

      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
